name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - macos-13
        - ubuntu-22.04
        - windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Set up Python and Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          if [[ ${{ matrix.os }} == 'macos-13' ]]; then
            pyinstaller --onefile main.py --name main-macos
          elif [[ ${{ matrix.os }} == 'windows-2022' ]]; then
            pyinstaller --onefile main.py --name main-windows.exe
          else
            pyinstaller --onefile main.py --name main-linux
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main-${{ matrix.os }}*
          name: github_api-${{ matrix.os }}
